name: Arcules API Audit Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  arcules-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq and curl
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Get Arcules token
        id: get_token
        run: |
          response=$(curl -s -X POST "https://msapi.jp.arcules.com/v1/login" \
            -H "accept: application/json" \
            -H "Content-Type: application/json" \
            -d "{\"email\":\"${{ secrets.ARCULES_EMAIL }}\",\"password\":\"${{ secrets.ARCULES_PASS }}\"}")
          echo "Response: $response"
          token=$(echo "$response" | jq -r '.jwtToken')
          echo "token=$token" >> $GITHUB_OUTPUT

      - name: Call Arcules APIs and generate HTML report
        run: |
          TOKEN=${{ steps.get_token.outputs.token }}
          if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
            echo "Failed to get token, aborting."
            exit 1
          fi

          echo "<html><body><h1>Arcules API Audit Report</h1>" > report.html

          endpoints=("devices" "organizations" "sites" "thumbnails")
          for ep in "${endpoints[@]}"; do
            url="https://msapi.jp.arcules.com/v1/$ep"
            http_status=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $TOKEN" "$url")
            echo "<h2>$ep</h2>" >> report.html
            echo "<p>HTTP Status: $http_status</p>" >> report.html

            if [ "$http_status" -eq 200 ]; then
              json=$(curl -s -H "Authorization: Bearer $TOKEN" "$url" | jq '.')
              echo "<pre>$json</pre>" >> report.html
            else
              echo "<p><span style='color:red'>Error or not found</span></p>" >> report.html
            fi
          done

          echo "</body></html>" >> report.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: arcules-api-audit-report
          path: report.html
