name: Arcules API Direct Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-arcules-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq and curl
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Get Arcules token
        id: get_token
        run: |
          response=$(curl -s -X POST "https://msapi.jp.arcules.com/v1/login" \
            -H "accept: application/json" \
            -H "Content-Type: application/json" \
            -d "{\"email\":\"${{ secrets.ARCULES_EMAIL }}\",\"password\":\"${{ secrets.ARCULES_PASS }}\"}")
          echo "Response: $response"
          token=$(echo "$response" | jq -r '.jwtToken')
          echo "token=$token" >> $GITHUB_OUTPUT

      - name: Call Arcules APIs
        id: call_apis
        run: |
          TOKEN=${{ steps.get_token.outputs.token }}
          if [ "$TOKEN" = "null" ] || [ -z "$TOKEN" ]; then
            echo "Failed to get token, aborting."
            exit 1
          fi

          echo "<html><body><h1>Arcules API Test Report</h1><ul>" > report.html

          # API エンドポイント一覧
          for endpoint in "devices" "organizations" "sites" "thumbnails"; do
            url="https://msapi.jp.arcules.com/v1/$endpoint"
            status=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $TOKEN" "$url")
            echo "<li>$endpoint : HTTP $status</li>" >> report.html
          done

          echo "</ul></body></html>" >> report.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: arcules-api-report
          path: report.html
